lumino/main/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path
import shared.views
import users.views
import django.views.i18n
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = (
    [
        path('i18n/', include('django.conf.urls.i18n')),
        path('setlang/<str:langcode>/', django.views.i18n.set_language, name='setlang'),
        path('django-rq/', include('django_rq.urls')),
    ]
    + i18n_patterns(
        path('admin/', admin.site.urls),
        path('', shared.views.index, name='index'),
        path('', include('accounts.urls')),
        path('subjects/', include('subjects.urls')),
        path('users/', include('users.urls')),
        path('user/edit/', users.views.edit_profile, name='edit-profile'),
        path('user/leave/', users.views.leave, name='leave'),
    ) 
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

lumino/subjects/urls.py
from django.urls import path, register_converter
from . import views, converters

app_name = 'subjects'
register_converter(converters.SubjectConverter, 'subject')
register_converter(converters.LessonConverter, 'lesson')

urlpatterns = [
    path('', views.subject_list, name='subject-list'),
    path('<subject:subject>/', views.subject_detail, name='subject-detail'),
    path('<subject:subject>/lessons/add/', views.add_lesson, name='add-lesson'),
    path('<subject:subject>/lessons/<lesson:lesson>/', views.lesson_detail, name='lesson-detail'),
    path('<subject:subject>/lessons/<lesson:lesson>/edit/', views.edit_lesson, name='edit-lesson'),
    path('<subject:subject>/lessons/<lesson:lesson>/delete/', views.delete_lesson, name='delete-lesson'),
    path('<subject:subject>/marks/', views.mark_list, name='mark-list'),
    path('<subject:subject>/marks/edit/', views.edit_marks, name='edit-marks'),
    path('enroll/', views.enroll_subjects, name="enroll-subjects"),
    path('unenroll/', views.unenroll_subjects, name="unenroll-subjects"),
    path('certificate/', views.request_certificate, name="request-certificate"),
]

lumino/subjects/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

from django.core.validators import MinValueValidator, MaxValueValidator

class Subject(models.Model):
    code = models.CharField(unique=True)
    name = models.CharField()
    teacher = models.ForeignKey(get_user_model(), related_name='teaching', on_delete=models.PROTECT)
    students = models.ManyToManyField(
        get_user_model(), related_name='enrolled', through='subjects.Enrollment'
    )

    def __str__(self, *args, **kwargs):
        return f'{self.code}'

    def get_absolute_url(self):
        return reverse('subjects:subject-detail', args={self})

class Lesson(models.Model):
    subject = models.ForeignKey(Subject, related_name='lessons', on_delete=models.CASCADE)
    title = models.CharField()
    content = models.TextField(blank=True)

    def __str__(self, *args, **kwargs):
        return f'{self.title}'
    
    def get_absolute_url(self):
        return reverse('subjects:lesson-detail', args={self.subject, self})

class Enrollment(models.Model):
    student = models.ForeignKey(
        get_user_model(), related_name='enrollments', on_delete=models.CASCADE
    )
    subject = models.ForeignKey(Subject, related_name='enrollments', on_delete=models.CASCADE)
    enrolled_at = models.DateField(auto_now_add=True)
    mark = models.PositiveSmallIntegerField(
        blank=True, null=True, validators=[MinValueValidator(1), MaxValueValidator(10)]
    )

    def __str__(self, *args, **kwargs):
        return f'{self.student} | {self.subject} | {self.mark} |{self.enrolled_at}'

lumino/subjects/forms.py
from django import forms
from .models import Subject, Enrollment, Lesson

class LessonsForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = ['title', 'content']

class EnrollSubjectsForm(forms.Form):
    subjects = forms.ModelMultipleChoiceField(
    queryset=None,
    widget=forms.CheckboxSelectMultiple,
    )

    def __init__(self, *args, **kwargs):
        student = kwargs.pop('student', None)
        super().__init__(*args, **kwargs)
        if student:
            self.fields['subjects'].queryset = Subject.objects.exclude(students=student)

class UnenrollSubjectsForm(forms.Form):
    subjects = forms.ModelMultipleChoiceField(
        queryset=None, 
        widget=forms.CheckboxSelectMultiple,
    )

    def __init__(self, *args, **kwargs):
        student = kwargs.pop('student', None)
        super().__init__(*args, **kwargs)
        if student:
            self.fields['subjects'].queryset = student.enrolled.all()

class EditMarkForm(forms.ModelForm):
    class Meta:
        model = Enrollment
        fields = ['mark']

lumino/subjects/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.forms import modelformset_factory
from django.shortcuts import redirect, render
from django.utils.translation import gettext as _

from users.models import Profile

from .forms import EditMarkForm, EnrollSubjectsForm, LessonsForm, UnenrollSubjectsForm
from .models import Enrollment, Lesson, Subject
from .tasks import deliver_certificate

FALLBACK_REDIRECT = 'index'
FORBIDDEN_MESSAGE = _("You don't have access")


def user_not_in_module(request, subject: Subject):
    if request.user.profile.role == Profile.Role.STUDENT:
        if request.user.enrollments.filter(subject=subject).count() == 0:
            raise PermissionDenied

    elif request.user.profile.role == Profile.Role.TEACHER:
        if subject.teacher != request.user:
            raise PermissionDenied


@login_required
def subject_list(request):
    if request.user.profile.role == Profile.Role.STUDENT:
        return student_subject_list(request)
    elif request.user.profile.role == Profile.Role.TEACHER:
        return render(request, 'subjects.html')


@login_required
def student_subject_list(request):
    modules_with_mark = request.user.enrollments.filter(mark__isnull=False).count()
    if modules_with_mark == request.user.enrollments.count() and modules_with_mark > 0:
        certificate = True
    else:
        certificate = False
    return render(request, 'subjects.html', dict(certificate=certificate))


@login_required
def subject_detail(request, subject: Subject):
    user_not_in_module(request, subject)
    if request.user.profile.role == Profile.Role.STUDENT:
        mark = request.user.enrollments.filter(subject=subject).get().mark
    elif request.user.profile.role == Profile.Role.TEACHER:
        mark = None
    return render(request, 'subject_detail.html', dict(subject=subject, mark=mark))


@login_required
def add_lesson(request, subject: Subject):
    if request.user.profile.role != Profile.Role.TEACHER:
        raise PermissionDenied
    user_not_in_module(request, subject)
    if request.method == 'POST':
        if (form := LessonsForm(request.POST)).is_valid():
            lesson = form.save(commit=False)
            lesson.subject = subject
            lesson.save()
            msg = _('Lesson was successfully added.')
            messages.success(request, msg)
            return redirect(subject)
    form = LessonsForm()
    return render(request, 'form.html', dict(form=form))


@login_required
def lesson_detail(request, subject: Subject, lesson: Lesson):
    user_not_in_module(request, subject)
    return render(request, 'lesson_detail.html', dict(subject=subject, lesson=lesson))


@login_required
def edit_lesson(request, subject: Subject, lesson: Lesson):
    if request.user.profile.role != Profile.Role.TEACHER:
        raise PermissionDenied
    user_not_in_module(request, subject)
    if request.method == 'POST':
        if (form := LessonsForm(request.POST, instance=lesson)).is_valid():
            form.save()
            msg = _('Changes were successfully saved.')
            messages.success(request, msg)
    form = LessonsForm(instance=lesson)
    return render(request, 'form.html', dict(form=form))


@login_required
def delete_lesson(request, subject: Subject, lesson: Lesson):
    if request.user.profile.role != Profile.Role.TEACHER:
        raise PermissionDenied
    user_not_in_module(request, subject)
    lesson.delete()
    msg = _('Lesson was successfully deleted.')
    messages.success(request, msg)
    return redirect(subject)


@login_required
def mark_list(request, subject: Subject):
    if request.user.profile.role != Profile.Role.TEACHER:
        raise PermissionDenied
    user_not_in_module(request, subject)
    modules = subject.enrollments.all()
    return render(request, 'mark_list.html', dict(modules=modules, subject=subject))


@login_required
def edit_marks(request, subject: Subject):
    if request.user.profile.role != Profile.Role.TEACHER:
        raise PermissionDenied
    user_not_in_module(request, subject)
    MarkFormSet = modelformset_factory(Enrollment, EditMarkForm, extra=0)
    queryset = subject.enrollments.all()
    if request.method == 'POST':
        if (formset := MarkFormSet(queryset=queryset, data=request.POST)).is_valid():
            formset.save()
            msg = _('Marks were successfully saved.')
            messages.success(request, msg)
    formset = MarkFormSet(queryset=queryset)
    return render(request, 'form.html', dict(form=formset, subject=subject))


@login_required
def enroll_subjects(request):
    if request.user.profile.role == Profile.Role.TEACHER:
        raise PermissionDenied
    if request.method == 'POST':
        if (form := EnrollSubjectsForm(request.POST, student=request.user)).is_valid():
            subjects_to_enroll = form.cleaned_data['subjects']
            request.user.enrolled.add(*subjects_to_enroll)
            msg = _('Successfully enrolled in the chosen subjects.')
            messages.success(request, msg)
            return redirect(FALLBACK_REDIRECT)
    else:
        form = EnrollSubjectsForm(student=request.user)
    return render(request, 'form.html', dict(form=form))


@login_required
def unenroll_subjects(request):
    if request.user.profile.role == Profile.Role.TEACHER:
        raise PermissionDenied
    if request.method == 'POST':
        if (form := UnenrollSubjectsForm(request.POST, student=request.user)).is_valid():
            subjects_to_remove = form.cleaned_data['subjects']
            request.user.enrolled.remove(*subjects_to_remove)
            msg = _('Successfully unenrolled from the chosen subjects.')
            messages.success(request, msg)
            return redirect(FALLBACK_REDIRECT)
    else:
        form = UnenrollSubjectsForm(student=request.user)
    return render(request, 'form.html', dict(form=form))


@login_required
def request_certificate(request):
    if request.user.profile.role == Profile.Role.TEACHER:
        raise PermissionDenied
    if request.user.enrollments.filter(mark__isnull=True).count() > 0:
        raise PermissionDenied
    deliver_certificate.delay(request.build_absolute_uri(), request.user)
    return render(request, 'deliver_certificate.html')

lumino/subjects/templates/certificate.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{{student.username}} grades</title>
</head>
<body>
  <h1>{{student.username}} grades</h1>
  <table>
    {% for enrollment in student.enrollments.all %}
    <tr>
      <th>{{ enrollment.subject }}</th>
      <td>{{ enrollment.mark }}</td>
    </tr>
    {% endfor %}
  </table>
</body>
</html>

lumino/subjects/templates/deliver_certificate.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<p>{% translate 'You will get the grade certificate quite soon at' %} {{ request.user.email }}</p>
{% endblock %}

lumino/subjects/templates/lesson_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% load markdownify %}
{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static "css/lesson_detail.css" %}">

<div class="container mb-4">
  <div class="row">
    <h2 class="col text-center mt-5 fw-bold">{{ lesson.title }}</h2>
  </div>
  <div class="row">
    <h2 class="col fs-5 border border-3 border-black rounded-3 mt-5 p-5 bg-primary-subtle fw-bold text-body-secondary">{{ lesson.content|markdownify }}</h2>
  </div>
</div>

<div class="container controls mb-5">
  <div class="row">
    {% if subject.teacher == request.user %}
      <div class="col rounded-3 text-center">
        <a href="{% url 'subjects:delete-lesson' subject lesson %}"><i class="bi bi-trash3-fill"></i></a>
      </div>
      <div class="col rounded-3 text-center">
        <a href="{% url 'subjects:edit-lesson' subject lesson %}"><i class="bi bi-pencil-square"></i></a>
      </div>
    {% endif %}
    <div class="col rounded-3 text-center">
      <a href="{{ subject.get_absolute_url }}">{% translate 'Go back' %}</a>
    </div>
  </div>
</div>
{% endblock %}
 

lumino/subjects/templates/mark_form.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<form method="post" novalidate>
  {% csrf_token %}
  {% for field in form %}
    <div class="fieldWrapper">
        {{ field.errors }}
        <h5>{{ field.instance.student.username|capfirst }}</h5>
        {{ field.label_tag }} {{ field }}
    </div>
  {% endfor %}
  <input type="submit" value="{% translate 'Save' %}">
</form>
{% endblock %}

lumino/subjects/templates/mark_list.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static "css/mark_list.css" %}">


<div class="container mb-4">
  <div class="row">
    <h2 class="col text-center mt-5">{{subject.code}} {% translate 'marks' %}</h2>
  </div>
</div>

<div class="container marksNav mb-5">
  <div class="row">
    <div class="col text-center">
      <a href={{ subject.get_absolute_url }}>{% translate 'Go back' %}</a>
    </div>
    <div class="col text-center">
      <a href="{% url 'subjects:edit-marks' subject %}">{% translate 'Edit marks' %}</a>
    </div>
  </div>
</div>
<div class="marks container p-3 text-center">
  {% for module in modules %}
    <p><a href="{{ module.student.profile.get_absolute_url }}">{{module.student.first_name}} {{module.student.last_name}}</a>: {{module.mark}}</p>
  {% empty %}
    <p>{% translate "This subject is empty" %}</p>
  {% endfor %}
</div>
{% endblock %}

lumino/subjects/templates/student_subjects.html
{% load i18n %}
{% load static %}

<link rel="stylesheet" href="{% static 'css/student_subjects.css' %}">

<div class="container titleNav mb-5">
  <div class="row">
    {% if certificate %}
      <div class="col text-center">
        <a href="{% url 'subjects:request-certificate' %}">{% translate 'Get your certificate of qualifications!' %}</a>
      </div>
    {% endif %}
    <div class="col text-center">
      <a href="{% url 'subjects:enroll-subjects' %}">{% translate 'Enroll in subjects' %}</a>
    </div>
    <div class="col text-center">
      <a href="{% url 'subjects:unenroll-subjects' %}">{% translate 'Unenroll in subjects' %}</a>
    </div>
  </div>
</div>

<div class="container">
  <div class="container">
    <div class="row">
      {% for subject in subjects %}
      <div class="col-sm-6 mb-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">{{ subject }}</h5>
            <h6 class="card-subtitle mb-2 text-body-secondary">{{ subject.name }}</h6>
            <a class="card-link" href="{{ subject.get_absolute_url }}">{% translate 'Details' %}</a>
          </div>
        </div>
      </div>
      {% empty %}
        <div class="row">
          <div class="col text-center"><p class="emptySubject">{% translate 'No subjects yet' %}</p></div>
        </div>
      {% endfor %}
    </div>
  </div>
</div>

lumino/subjects/templates/subject_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% load static%}

{% block content %}

<link rel="stylesheet" href="{% static 'css/subject_detail.css' %}">

<div class="container mb-4">
  <div class="row">
    <h2 class="col mt-5 fs-1 text-center fw-bold">{{subject.code}}: {{subject.name}}</h2>
  </div>
  <div class="row">
    <h2 class="col fs-3 text-center fw-bold text-body-secondary">{% translate 'Teacher:' %} {{subject.teacher}}</h2>
  </div>
</div>

{% if user.profile.role == 'S' and mark %}
  <p>{% translate 'Your mark for this subject:' %} {{ mark }}</p>
{% endif %}

<div class="container titleNav mb-5">
  <div class="row">
    <div class="col text-center">
      <a href="{% url 'subjects:subject-list' %}">{% translate 'Go back' %}</a>
    </div>
    {% if user.profile.role == 'T' %}
      <div class="col text-center">
        <a href="{% url 'subjects:mark-list' subject %}">{% translate 'See all marks' %}</a>
      </div>
      <div class="col text-center">
        <a href="{% url 'subjects:add-lesson' subject %}">{% translate 'New lesson' %}</a>
      </div>
    {% endif %}
  </div>
</div>

{% if subject.lessons %}
  <div class="lessons">
{% for lesson in subject.lessons.all %}
  <ul class="list-group">
    <li class="list-group-item d-flex align-items-center my-3 container-fluid">
      <b class="col">{{lesson.title}}</b>
      <span class="col justify-content-end">
        <span class="badge text-bg-primary rounded-pill">
          <a class="p-2" href="{% url 'subjects:lesson-detail' subject lesson %}">{% translate 'Details' %}</a>
        </span>
        {% if user.profile.role == 'T' %}
          <span class="badge text-bg-warning rounded-pill">
              <a class="p-2" href="{% url 'subjects:edit-lesson' subject lesson %}">{% translate 'Edit lesson' %}</a>
          </span>
          <span class="badge text-bg-danger rounded-pill">
              <a class="p-2" href="{% url 'subjects:delete-lesson' subject lesson %}">{% translate 'Delete lesson' %}</a>
          </span>
        {% endif %}
      </span>
    </li>

  </ul>
{% endfor %}
  </div>
{% else %}
  <p>{% translate 'There is no lessons yet' %}</p>
{% endif %}
{% endblock %}

lumino/subjects/templates/subjects.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
  <div class="container mb-4">
    <div class="row">
      <h2 class="col text-center mt-5">{% translate 'My subjects' %}</h2>
    </div>
  </div>
  {% if user.profile.role == 'S' %}
    {% include 'student_subjects.html' %}
  {% elif user.profile.role == 'T' %}
    {% include 'teacher_subjects.html' %}
  {% endif %}
{% endblock %}

lumino/subjects/templates/teacher_subjects.html
{% load i18n %}
<div class="container">
  <div class="row">
    {% for subject in subjects %}
    <div class="col-sm-6 mb-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{ subject }}</h5>
          <h6 class="card-subtitle mb-2 text-body-secondary">{{ subject.name }}</h6>
          <a class="card-link" href="{{ subject.get_absolute_url }}">{% translate 'Details' %}</a>
        </div>
      </div>
    </div>
    {% empty %}
      <div class="row">
        <div class="col text-center"><p class="emptySubject">{% translate 'No subjects yet' %}</p></div>
      </div>
    {% endfor %}
  </div>
</div>