lumino/main/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path
import shared.views
import users.views
import django.views.i18n
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = (
    [
        path('i18n/', include('django.conf.urls.i18n')),
        path('setlang/<str:langcode>/', django.views.i18n.set_language, name='setlang'),
        path('django-rq/', include('django_rq.urls')),
    ]
    + i18n_patterns(
        path('admin/', admin.site.urls),
        path('', shared.views.index, name='index'),
        path('', include('accounts.urls')),
        path('subjects/', include('subjects.urls')),
        path('users/', include('users.urls')),
        path('user/edit/', users.views.edit_profile, name='edit-profile'),
        path('user/leave/', users.views.leave, name='leave'),
    ) 
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

lumino/subjects/urls.py
from django.urls import path, register_converter
from . import views, converters

app_name = 'subjects'
register_converter(converters.SubjectConverter, 'subject')
register_converter(converters.LessonConverter, 'lesson')

urlpatterns = [
    path('', views.subject_list, name='subject-list'),
    path('<subject:subject>/', views.subject_detail, name='subject-detail'),
    path('<subject:subject>/lessons/add/', views.add_lesson, name='add-lesson'),
    path('<subject:subject>/lessons/<lesson:lesson>/', views.lesson_detail, name='lesson-detail'),
    path('<subject:subject>/lessons/<lesson:lesson>/edit/', views.edit_lesson, name='edit-lesson'),
    path('<subject:subject>/lessons/<lesson:lesson>/delete/', views.delete_lesson, name='delete-lesson'),
    path('<subject:subject>/marks/', views.mark_list, name='mark-list'),
    path('<subject:subject>/marks/edit/', views.edit_marks, name='edit-marks'),
    path('enroll/', views.enroll_subjects, name="enroll-subjects"),
    path('unenroll/', views.unenroll_subjects, name="unenroll-subjects"),
    path('certificate/', views.request_certificate, name="request-certificate"),
]

lumino/users/urls.py
from django.urls import path, register_converter
from . import views, converters

app_name = 'users'
register_converter(converters.ProfileConverter, 'user')

urlpatterns = [
    path('<user:user>/', views.user_detail, name='user-detail'),
]

lumino/shared/models.py
from django.db import models

# Create your models here.

lumino/shared/views.py
from django.shortcuts import render, redirect

def index(request):
    if request.user.username:
        return redirect('subjects:subject-list')
    
    else:
        return render(request, 'index.html')

lumino/shared/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Lumino</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
</head>
<body>
  <div class="container-fluid">
    {% include 'header.html' %}
    {% include 'messages.html' %}
    {% block content %}
    {% endblock %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
</body>
</html>

lumino/shared/templates/form.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static "css/form.css" %}">

<form method="post" enctype="multipart/form-data" novalidate>
  {% csrf_token %}
  <div class="form">
    {{ form.as_p }}
  </div>

  <div class="container footerForm mb-5">
    <div class="row">
      <div class="col text-center">
        <input type="submit" value="{% translate 'Save' %}">
      </div>
      <div class="col text-center">
        <a href="javascript:history.back()">{% translate 'Go back' %}</a>
      </div>
    </div>
  </div>
</form>
{% endblock %}

lumino/shared/templates/header.html
{% load shared_extras %}
{% load i18n %}
{% load static %}

<link rel="stylesheet" href="{% static 'css/header.css' %}">

<nav class="navbar navbar-expand-lg sticky-top bg-body-tertiary">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a href="{% url 'index'%}" class="navbar-brand logo-link align-content-center">
      <h1 class=""><i class="bi bi-mortarboard-fill me-2 ms-5">Lumino</i></h1>
    </a>
    {% if user.is_authenticated %}
      <div class="collapse navbar-collapse container" id="navbarTogglerDemo03">
        <ul class="navbar-nav justify-content-center row">
          <li class="nav-item mx-2 col">
            <button class="btn btn-outline-primary buttons"><a class="" href="{% url 'subjects:subject-list' %}">{% translate 'Subjects' %}</a></button>
          </li>
          <li class="nav-item mx-2 col">
            <button class="btn btn-outline-primary buttons"><a class="" href="{% url 'users:user-detail' request.user.profile %}" title="{% translate 'Profile' %}">{{user.first_name}}</a></button>
          </li>
          <li class="nav-item mx-2 col">
            {% setlang %}
          </li>
          <li class="nav-item mx-2 col">
            <button class="btn btn-outline-primary buttons"> <a href="{% url 'logout' %}">{% translate 'logout' %}</a></button>
          </li>
        </ul>
      </div>
    {% endif %}
  </div>
</nav>

lumino/shared/templates/index.html
{% extends 'base.html'%}
{% load i18n %}
{% load static %}

{% block content %}
  <link rel="stylesheet" href="{% static 'css/index.css' %}">
  <h1 class="h2 mb-4 text-center">{% translate 'Join Lumino. The cool education platform!'%}</h1>
  <div class="auth mt-5">
    <a href="{% url 'login' %}">{% translate 'login' %}</a>
    <a href="{% url 'signup' %}">{% translate 'signup' %}</a>
  </div>
{% endblock %}

lumino/shared/templates/messages.html
{% if messages %}
  <ul class="messages">
      {% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
              {{ message }}
          </li>
      {% endfor %}
  </ul>
{% endif %}